version: "3.8"
services:
  # front:
  #   build: ./web/front
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - './web/front:/usr/src/app'
  #   networks:
  #     - my-network
  back:
    build: ./web/back
    ports:
      - "5000:5000"
    volumes:
      - ./web/back:/code
    environment:
      FLASK_ENV: development
    networks:
      - my-network

networks:
  my-network:
    driver: bridge